$clean_ext = 'bbl exitCode run.xml sh stderr stdout synctex';
$pdf_mode = 5;
$postscript_mode = $dvi_mode = 0;
$xelatex = 'xelatex -no-pdf -shell-escape -synctex=15 %O %S';

@default_files = ('lab-notebook.tex');
